### ISSUE TITLE
Do you know how to read output.w2l file?

### ISSUE THREAD

**Issue by kjrathore** [rmlz/cqw2calibtool#2]
Hi,

I am looking to read vector plot output file (output.w2l) a binary file from CE-QUALS-W2.
Any ideas?

**Comment by rmlz** [comment]
Hello kjrathore.

Can you please tell me more what you want to achieve?
It has been a while since I have finished and published this project, and - as I recall-  the output files were all .opt 

I never heard of a output.w2l file before.

**Comment by rmlz** [comment]
I am closing this issue as I sent you a private message.
